### ISSUE TITLE
BD Création

### ISSUE THREAD

**Issue by Lindwing** [WhatEatInc/WhatEat-back#27]
### Description
Création d’un nouveau cluster sur MangoDB

### Tâches
- [x] Création d'un Cluster

### Durée
| Optimiste  | Pessimiste   | Attentu  | Effecuté ✔️ |
|------------|-------------|----------|---------|
|                  |                    |              |               |

### Dépendances d'autres tâches

- #xx
- #xx

**Comment by JBA-HEIG** [comment]
This issue has been solved  a while ago ... closing it
