### ISSUE TITLE
BD Communication

### ISSUE THREAD

**Issue by Lindwing** [WhatEatInc/WhatEat-back#28]
### Description
Utilisation de Mangoose pour la communication

### Tâches
- [x] Mise en place de Mangoose

### Durée
| Optimiste  | Pessimiste   | Attentu  | Effecuté ✔️ |
|------------|-------------|----------|---------|
|                  |                    |              |               |

### Dépendances d'autres tâches

- #xx
- #xx

**Comment by JBA-HEIG** [comment]
This issue has been solved a while ago .... closing it
