### ISSUE TITLE
Log-Out

### ISSUE THREAD

**Issue by Lindwing** [WhatEatInc/WhatEat-back#48]
### Description
L'utilisateur peut se déconnecter.

### Tâches

- [x] Invalide le JWT

### Durée

| Optimiste | Pessimiste | Attentu | Effecuté ✔️ |
| --------- | ---------- | ------- | ----------- |
|           |            |         |             |

### Dépendances d'autres tâches

- #xx
- #xx

**Comment by JBA-HEIG** [comment]
I'll do it rn

**Comment by JBA-HEIG** [comment]
see above
