### ISSUE TITLE
Ajouter endpoints

### ISSUE THREAD

**Issue by hadrylouis** [WhatEatInc/WhatEat-back#60]
### Description
- Ajouter un endpoint pour les allergies
- Ajouter un endpoint pour les particularités
- Ajouter un endpoint pour les cuisines préférées
- Ajouter un endpoint pour les durations

### Durée

| Optimiste | Pessimiste | Attentu | Effecuté ✔️ |
| --------- | ---------- | ------- | ----------- |
|           |            |         |             |

**Comment by JBA-HEIG** [comment]
I'll do it rn

**Comment by hadrylouis** [comment]
Please add durations endpoint

**Comment by JBA-HEIG** [comment]
Yep, working on it @hadrylouis
