### ISSUE TITLE
Improve code complexity

### ISSUE THREAD

**Issue by hadrylouis** [WhatEatInc/WhatEat-back#67]
### Description
In the recipe controller, inside method `removeUselessAttr(results)` there is a nested loop. Please improve this in a single loop
You can create un new object for each recipe and keep only the needed params.

### Durée

| Optimiste | Pessimiste | Attentu | Effecuté ✔️ |
| --------- | ---------- | ------- | ----------- |
|           |            |         |             |

**Comment by JBA-HEIG** [comment]
already fixed a while ago, closing it.
